languageCode = "en"
languageName = "English"
weight = 1
title = "Romain Lespinasse"

[params]
  displayName = "English"
  isoCode = "en"
  dateFormat = "Jan 2, 2006"
  description = "Technical Posts, Opensource Releases, and sometimes Games-related stuff"

[params.author]
  name = "Romain Lespinasse"
  image = "img/rlespinasse.jpg"
  headline = "Technical Posts, Opensource Releases, and sometimes Games-related stuff"
  links = [
    { github = "https://github.com/rlespinasse" },
    { gitlab = "https://gitlab.com/rlespinasse" },
    { linkedin = "https://www.linkedin.com/in/romain-lespinasse" },
  ]
