# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

disableImageOptimization = false

highlightCurrentMenuArea = true
smartTOC = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 4
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = false

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = false
  showHero = true
  heroStyle = "big"
  showBreadcrumbs = false
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = false
  showZenMode = false

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true
  cardView = false

[taxonomy]
  showTermCount = true
  showBreadcrumbs = false
  showTableOfContents = false
  cardView = true

[term]
  showBreadcrumbs = false
  showTableOfContents = false
  groupByYear = true
  cardView = false

[analytics]
  goatCounter = "rlespinasse"
