baseURL = "https://www.romainlespinasse.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Romain Lespinasse"
theme = "archie"
copyright = "© Romain Lespinasse"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Technical Posts, Opensource Releases, and sometimes Games Creations"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rlespinasse"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/romain-lespinasse"
 
[[params.social]]
name = "Bluesky"
icon = "cloud"
url = "https://bsky.app/profile/rlespinasse.bsky.social"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "OSS"
url = "/oss"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
