name: Release Notes as Posts

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight (UTC)
  workflow_dispatch:
  pull_request:
    paths:
      - "release-notes-as-posts.sh"
      - ".github/workflows/release-notes-as-posts.yaml"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-notes-as-posts
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: taiki-e/install-action@a57ddfbcd928cf9406a78dcc300dacc5d367a547 # v2.68.31
        with:
          tool: just

      - run: just release-notes-as-posts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "chore(posts): sync release notes as posts"
